### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hclimente** [hclimente/cookiecutter-bioML#1]
- [ ] Parse YAML in the nextflow to get the classifiers
- [x] Add mode (classification/regression)
- [x] Fix final output
- [x] Add additional analysis methods
  - [x] MSE
  - [x] Accuracy, sensitivity and specificity
- [x] Fix simulations' covariance
- [x] Classifiers overwrite feature selector's output
